### ISSUE TITLE
How to retrieve shipping contact details from apple pay

### ISSUE THREAD

**Issue by omar-selo** [flutter-stripe/flutter_stripe#1044]
I'm using `presentApplePay` for Apple Pay and passing `ApplePayContactFieldsType.name` to `requiredShippingAddressFields` parameter to get the user's name from apple pay. However I'm not sure how I should retrieve this name because `presentApplePay` itself doesn't return anything. We can't use `onDidSetShippingContact` of `presentApplePay` because we only get [obfuscated](https://developer.apple.com/design/human-interface-guidelines/technologies/apple-pay/handling-errors) data from apple which empties the name. Apple pay would only allow access to the name when the user authorizes the payment. But at that point `onDidSetShippingContact` isn't called and I can't figure out where to get this information from.

Smartphone / tablet
- Device: iPhone 8
- OS 15.5
- Package version: 7.0.0
- Flutter version 3.3.8

**Comment by remonh87** [comment]
You are correct, this library does not facilitate it because the payment will be authorised outside this library's context. The Stripe client sdk's goal is collecting data to complete payments. However the name will be set on the payment intent in Stripe and you can access it through your backend.  See screenshot:

![Screenshot 2022-11-29 at 21 16 18](https://user-images.githubusercontent.com/20230599/204649842-1835226a-32ef-42b8-8ea6-00cb71958028.png)
