### ISSUE TITLE
Stripe Sdk has not been initialised

### ISSUE THREAD

**Issue by fluttermoonger** [flutter-stripe/flutter_stripe#1082]
**Describe the bug**
When trying to add the Card widget and use it I get the following error where I use the widget:

> Unhandled Exception: PlatformException(error, lateinit property stripeSdk has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property stripeSdk has not been initialized.

**To Reproduce**
1. Install flutter_stripe
2. Add Stripe.publishablekey = **YOUR KEY** in main.dart before run()
3. Add the Card widget in your UI
4. Go to the widget

**Expected behavior**
The behaviour should be that it works according to documentation.

**Smartphone / tablet**
 - Device: Android emulator
 - Package version: 7.0.0
 - Flutter version: 3.3.6

**Additional context**
Running kotlin above 1.5
complieSdk is version 33
minSdk is version 23

**Comment by fluttermoonger** [comment]
There was stuff in the setup guide missing. Change in Kotlin and style.xml file and also init stripe after the stripe.publishable key

**Comment by remonh87** [comment]
thanks for bringing this too my attention. You are not the first running into this issue, unfortunately we cannot change this due to technical limitations.  We have a[ troubleshoot guide: ](https://docs.page/flutter-stripe/flutter_stripe/troubleshooting#the-plugin-is-crashing-with-a-platformexception-on-android-on-ios-it-is-working-fine) , did this information not help you?
