### ISSUE TITLE
CardFormField style broken

### ISSUE THREAD

**Issue by jamesdixon** [flutter-stripe/flutter_stripe#1143]
**Describe the bug**
`CardFormField`'s `CardFormStyle` only seems to be working with cursor color and background. All other attributes are ignored.

**To Reproduce**
Try the following code:

```
          CardFormField(
            autofocus: true,
            style: CardFormStyle(
              cursorColor: Colors.orange,
              borderColor: Colors.green,
              borderRadius: 50,
              borderWidth: 10,
              textErrorColor: Colors.yellow,
              placeholderColor: Colors.pink,
              backgroundColor: Colors.white,
              textColor: Colors.white,
              fontSize: 25
            ),
          ),
```

You'll notice that the only attributes that appear to change are background and cursor color. The rest don't function.

**Expected behavior**
Styling on the form would match the attributes.

**Smartphone / tablet**
 - Device: iPhone 14 Pro
 - OS: iOS 16
 - Package version: [8.0.0+1](https://github.com/flutter-stripe/flutter_stripe/tree/8.0.0%2B1)
 - Flutter 3.3.7

**Additional context**
I haven't yet tried this on Android.

**Comment by remonh87** [comment]
This is correct behaviour enforced by the stripe sdk: see inline comment https://github.com/flutter-stripe/flutter_stripe/blob/6cdf95e6c0e6772f51fc0a92956174f658278a5c/packages/stripe/lib/src/widgets/card_form_field.dart#L41

**Comment by Flucadetena** [comment]
Hi, I know this has been reported many times and stripe does not want to fix it.

I realized that the text, borders,... everything depends on the "system mode" on IOS. An not the theme of your app. (Which makes no sense).

But is there not a way to change the "Brightness" that the native CardFormField takes, instead of just taking it from the system?

That way the problem would be solved, more or less.
