### ISSUE TITLE
[Stripe-Checkout] android white screen. 

### ISSUE THREAD

**Issue by MonsterDKing** [flutter-stripe/flutter_stripe#1206]
**Describe the bug**
How about I have a relatively new project. (with 1 month) totally implement the checkout library to do on ios it works perfectly and everything but on android the screen turns completely white

and the debug gives me this error:
I/chromium(10913): [INFO:CONSOLE(1)] "Unrecognized feature: 'payment'.", source: https://js.stripe.com/v3/ (1)

**To Reproduce**
1. Entering number 123-456-789 into the cardfield.
2. Tapping the confirm button.
3. Observe a failure with exception (including the part of the stack trace, belonging to this package) …
I/chromium(10913): [INFO:CONSOLE(1)] "Unrecognized feature: 'payment'.", source: https://js.stripe.com/v3/ (1)

**Expected behavior**
cast checkout view in webview

**Smartphone / tablet**
 - Device: Pixel 2 
 - OS: Android 13
 - Package version: 1.0.0
 - Flutter version  3.7.1

**Additional context**

**Comment by remonh87** [comment]
I do not think that is the issue, because I have the same info log and successfully. Note that 123 456 789 is not a valid number. You can use one of the testcards like: 4242 4242 4242 4242. 

Also check our example implementation: https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/checkout/checkout_screen.dart

If you have a reproducible scenario feel free to reopen it and ping me

**Comment by SayedMainUddin** [comment]
and the debug gives me this error:
I/chromium(10913): [INFO:CONSOLE(1)] "Unrecognized feature: 'payment'.", source: https://js.stripe.com/v3/ (1)

Same problem in my android app too.
