### ISSUE TITLE
Add translation or custom label to PaymentSheet

### ISSUE THREAD

**Issue by Pablo-Aldana** [flutter-stripe/flutter_stripe#121]
**Is your feature request related to a problem? (please describe)**
Currently is not possible to setup a language or custom labels to the payment_sheet

**Describe the solution you'd like**
Ability to have i18n or add custom labels for the fields on payment_sheets

**Describe alternatives you've considered**
make the labels configurable i.e Card information could be part of  SetupPaymentSheetParameters  or PresentPaymentSheetParameters

```
await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          applePay: true,
          googlePay: true,
          style: ThemeMode.dark,
          testEnv: true,
          merchantCountryCode: 'DE',
          merchantDisplayName: 'Flutter Stripe Store Demo',
          customerId: _paymentSheetData!['customer'],
          paymentIntentClientSecret: _paymentSheetData!['paymentIntent'],
          customerEphemeralKeySecret: _paymentSheetData!['ephemeralKey'],
         cardInformationLabel: "My Custom Label or Translation",
         cardNumberLabel: "My Custom Label or Translation",
         expirationLabel: "My Custom Label or Translation",
         countryLabel: "My Custom Label or Translation",
        selectedCountry: "Spain",
        ZIPLabel: "My custom label or Translation"

        ),
```
**Additional context**

**Comment by thorsten-stripe** [comment]
Payment sheet localisation happens automatically based on device language. See https://github.com/stripe/stripe-react-native/issues/243#issuecomment-849701446

**Comment by Pablo-Aldana** [comment]
Thanks a lot @thorsten-stripe it actually worked, I was changing the device language but didn't know I had to update Xcode as well. 

However what did not change was the country selector that still select as pre default US. I can say in the Pay plugin there is a json configuration file that I suppose changes this behaviour, but I can see from SetupPaymentSheetParameters how can I pass this file or modify this information

I will keep an eye on the issue you have shared as it is an interesting option to customise the translation.

**Comment by SlavisDEV** [comment]
@thorsten-stripe this does not work. I set Xcode language but nothing has changed. 
Android works well (polish language).

**Comment by maganap** [comment]
@thorsten-stripe Can device language be overridden? Our app is forced to Spanish only, so I'd like to force the payment sheet and error messages to Spanish as well, just to keep the app consistent. Thanks

**Comment by maganap** [comment]
@remonh87 Thanks a lot for your suggestion. I just checked and we are indeed setting `merchantCountryCode: ES`, and the country selector is certainly in "Spain" by default. But the language is still English.
I just changed my phone language to Spanish just to test, same result, English.
Maybe I'm missing some Flutter localization settings or something? :-/

**Comment by maganap** [comment]
@remonh87 I must have done something wrong before because now it's working. Sorry about that.

On the other hand, I did find 2 things:
- There's a missing translation to Spanish for Android (but it's fine in iOS). It's the "Card Information" label above the card number field. The rest of the sheet is indeed translated.
- The error messages are not being translated. For example, when closing the sheet without paying, an `StripeException` is received with a `LocalizedErrorMessage`. The `localizedMessage` property is supposed to be translated, but not in my case. I'll dig a little further to see if there's something else I might be missing. Otherwise I'll open another issue for that.

Thanks!

**Comment by remonh87** [comment]
@maganap  the localized messages are coming from the native Stripe sdk so if things are missing I think it is best to open a ticket to their respective iOS or Android sdk. The paymentsheet is maintained and created by stripe and we only created the bridge from native to flutter. Btw I am happy to put the issues under Stripe's attention once created so feel free to ping me

**Comment by maganap** [comment]
@remonh87  I didn't want to report both things together, so here you are:

iOS: https://github.com/stripe/stripe-ios/issues/1964
Android: https://github.com/stripe/stripe-android/issues/5014

Please feel free to complement the iOS report with your knowledge, because I really felt I couldn't give information enough to them. I can tell, though, the untranslated error messages happen in both, Android and iOS, so I guess the problem is even further down.

Thank you!

**Comment by remonh87** [comment]
thanks @maganap  I will subscribed to both issues and will follow it in case some extra info is required I will help you out. Thanks for filing the tickets!

**Comment by hinrikHelga** [comment]
Any update to this? As in being able to set the locale ourselves instead of having to depend on the device locale?

**Comment by MuhammadMusa22** [comment]
Any update to this? As in being able to set the locale ourselves instead of having to depend on the device locale?

**Comment by ChandAbdullah** [comment]
We need locale support within the package 

`locale: 'es'` like that


Also `merchantCountryCode ` has been removed in the latest version [flutter_stripe: ^9.4.0](https://pub.dev/packages/flutter_stripe)

**Comment by remonh87** [comment]
The locale will always default to the locale of the phone this is a decision made by Stripe and outside our power. When they will change this behaviour it will automatically be available in this SDK.
