### ISSUE TITLE
Bump checkout version

### ISSUE THREAD

**Issue by Andrflor** [flutter-stripe/flutter_stripe#1249]
stripe_checkout version 1.0.0 was release one year ago (flutter stripe v3).
Since then a bunch of features were added.

Can you bump the version so we can have those changes on pub.dev ?
I need the accountId feature especially but it's not available on the pub.dev version.

**Comment by Andrflor** [comment]
Wow never got that so insanely misunderstood, or was i even read ?

On pub.dev stripe_checkout is from one year ago.
![image](https://github.com/flutter-stripe/flutter_stripe/assets/32484588/061831fe-7865-4437-821d-5bcd6b2e364d)

Please release a new version on pub.dev so i can use it instead of using a github url...

**Comment by jamesblasco** [comment]
Hi @Andrflor, we are going to discontinue Checkouts in order to use [Payment Links](https://stripe.com/payments/payment-links). This provides a straight way to implement payments without no native integration needed from the app, just launching the url, similar to checkouts.

If you prefer you have the checkout flow integrated in your app I would recommend you to use 
PaymentSheet for mobile and Payment Element for web. 

Could you describe a bit more how are you using checkouts in your project?
