### ISSUE TITLE
Google pay doesn't appear

### ISSUE THREAD

**Issue by mostafaalimorsy** [flutter-stripe/flutter_stripe#1326]
Hi, I use Stripe v 9.2.2 and it is working as well but google pay doesn't appear I test it on Android 9, 11, and 12 and it just shows up on Android 12

**Comment by remonh87** [comment]
please use the issue template and provide some more context information. You need to make sure that you have a valid payment card configured  on your android phone

**Comment by igrik12** [comment]
I am experiencing a similar issue

#### Describe the bug
On Android 13 devices, the "Google Pay" button does not appear on the "Payment Sheet" when using the Flutter code snippet provided. However, the same code works fine on Android 12 devices.

#### To Reproduce
Steps to reproduce the behavior:

1. Use the following Flutter code snippet to initialize the payment sheet:
``` dart
await Stripe.instance.initPaymentSheet(
  paymentSheetParameters: SetupPaymentSheetParameters(
    paymentIntentClientSecret: clientSecret,
    merchantDisplayName: 'Eldinero',
    customerId: customerId,
    customerEphemeralKeySecret: ephemeralKey,
    googlePay: const PaymentSheetGooglePay(
      merchantCountryCode: "NZ",
      currencyCode: "nzd",
      testEnv: !kReleaseMode,
    ),
    billingDetails: const BillingDetails(
      address: Address(
        country: 'US',
        city: '',
        line1: '',
        line2: '',
        state: '',
        postalCode: '',
      ),
    ),
    style: ThemeMode.dark,
  ),
);
```
Run the app on an Android 13 device.
Observe that the "Google Pay" button does not appear on the "Payment Sheet".

#### Expected behavior
The "Google Pay" button should appear on the "Payment Sheet" when running the app on both Android 12 and Android 13 devices.

#### Smartphone / tablet
Device: OnePlus 9 LE2113
OS: Android 13
Package version: flutter_stripe: 9.2.2
Flutter version: 3.10.6

#### Additional context
"Google Pay" is working correctly with a standalone package [pay ](https://pub.dev/packages/pay) on both Android 12 and Android 13 devices.

**Comment by mostafaalimorsy** [comment]
it work with Android 12 but on android 11 or 9 the button does not appear 
![Screenshot from 2023-07-29 11-30-17](https://github.com/flutter-stripe/flutter_stripe/assets/35115832/defcea32-3a47-4920-856d-243a25696a44)

@remonh87 @igrik12

**Comment by remonh87** [comment]
I tried to reproduce it on my pixel android 13 phone but still see the google pay button. Did you configure a payment card on the phone itself and also did you run it on test mode or production mode.  

Also can you try running our example app and check if the paymentsheet is shown there?

**Comment by mostafaalimorsy** [comment]
hi, thanks for your response the issue was must the device has a Google account with a pay option enabled to can show the google pay button
