### ISSUE TITLE
pub failed after adding this plugin

### ISSUE THREAD

**Issue by expertdev-designer** [flutter-stripe/flutter_stripe#139]
i am getting issue when i get pub with this plugin

Because geolocator >=6.1.4 <7.0.0-nullsafety.0 depends on geolocator_platform_interface ^1.0.8 which depends on plugin_platform_interface ^1.0.2, geolocator >=6.1.4 <7.0.0-nullsafety.0 requires plugin_platform_interface ^1.0.2.
And because google_map_location_picker >=4.1.3 depends on geolocator ^6.1.14, google_map_location_picker >=4.1.3 requires plugin_platform_interface ^1.0.2.
And because flutter_stripe >=1.0.2 depends on stripe_platform_interface ^1.0.2 which depends on plugin_platform_interface ^2.0.0, google_map_location_picker >=4.1.3 is incompatible with flutter_stripe >=1.0.2.
So, because "Projectname" depends on both google_map_location_picker ^4.1.7 and flutter_stripe ^1.0.2, version solving failed.
pub get failed (1; So, because Projectname depends on both google_map_location_picker ^4.1.7 and flutter_stripe ^1.0.2, version solving failed.)

How i can solve this? Please help

**Comment by jamesblasco** [comment]
The problem is that the package [google_map_location_picker](https://pub.dev/packages/google_map_location_picker)  is using an old version of the geolocator package that does not use the new plugin_plaftorm_interface with null-safety support. 

https://github.com/humazed/google_map_location_picker
The developer has not been updating this library since March, you should consider remove it from your project or fork it and use a custom version with the dependencies updated like https://github.com/humazed/google_map_location_picker/pull/153
