### ISSUE TITLE
About cvc_re_collection_screen.dart

### ISSUE THREAD

**Issue by galvin59** [flutter-stripe/flutter_stripe#1406]
Hi

About the cvc_re_collection_screen.dart screen in the example app.
I looked at this file because I want the user to type again his CVC, for safety reason, before using a saved card.
As far as I see, the screen asks the user for a CVC, stored in the _cvc variable, but this variable is never used later ? 🤔
Nor in the async or sync payment methods
Or am I missing something ??
Thanks

Julien

**Comment by remonh87** [comment]
no this is not possible due to safety reasons. If you would process the cvc code yourself you need to be compliant to a higher level of psi compliance. If you are a startup or scale up the amount of paperwork for that is unbearable and that is why stripe has build in pci compliant UI . 

 If the user will enter a wrong cvc number stripe is smart enough to notice that it is invalid and also that someone tries to guess the cvc by using some bot :) . For more information I would recommend to contact Stripe support how to make this safe :) .
