### ISSUE TITLE
[PAYMENT METHOD] Unable to create a payment method for connected account

### ISSUE THREAD

**Issue by mike392** [flutter-stripe/flutter_stripe#141]
Hi, Team,

When i use `Stripe.instance.createPaymentMethod(PaymentMethodParams.card())` in order to create PaymentMethod for a ConnectedAccount of a particular user.

Generally is there a way to create a PaymentMethod for a ConnectedAccount?

```
Stripe.stripeAccountId = "acct_*";
await Stripe.instance.applySettings();
```

and 

```
Stripe.instance.createPaymentMethod(PaymentMethodParams.card(), {"Stripe-Account": "acct_*"})
```
do not work - because on backend when i try to `attach` paymentMethod to a Customer object there is error:
```
No such PaymentMethod: 'pm_*'; OAuth key or Stripe-Account header was used but API request was provided with a platform-owned payment method ID. Please ensure that the provided payment method matches the specified account
```

It clearly states that `createPaymentMethod` creates a payment method on behalf of a platform account. 
Moreover, as far as i know it is a bad practice to use AccountID on the client - but i didn't know any other way how to try to make it work. And still it doesn't...

Can you, please, advise me on that?

Thank you so much in advance!
Best regards,
Mikhail

**Comment by jamesblasco** [comment]
Could you create the payment intent from your server with the appropriate params and use `confirmPaymentMethod` instead of `createPaymentMethod` as recommended in the official docs?

Official Guide: 
https://stripe.com/docs/payments/integration-builder
Flutter Example: 
https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/webhook_payment_screen.dart
