### ISSUE TITLE
Issue with apple pay button 

### ISSUE THREAD

**Issue by atulproject99** [flutter-stripe/flutter_stripe#1855]
**Describe the bug**
When I click on the Apple Pay button, it closes and reopens the payment sheet in real device. But simulator, it showing the apple pay cards

**Expected behavior**
It will open apple pay bottom sheet but not just do close payment sheet for little bit then open it again on real device.

**Smartphone / tablet**

 - Package version:Latest
 - Flutter version - Latest 

**Additional context**
///  2. initialize the payment sheet
    try {
      await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          merchantDisplayName: 'AdRent',

          paymentIntentClientSecret: clientSecret,

          primaryButtonLabel: 'Pay now',
          style: ThemeMode.light,
          //customFlow: Platform.isIOS ? false : true,
          applePay: const PaymentSheetApplePay(
              merchantCountryCode: 'GB', buttonType: PlatformButtonType.pay),
          googlePay: const PaymentSheetGooglePay(
              merchantCountryCode: 'GB', testEnv: false, currencyCode: 'GBP'),
          appearance: PaymentSheetAppearance(
            colors: PaymentSheetAppearanceColors(
              background: AppColors.baseColor,
              primary: AppColors.blueColor,
              icon: AppColors.blueColor,
              componentDivider: AppColors.greyColor,
              componentBackground: AppColors.baseColor,
              componentText: AppColors.blackTextColor,
              primaryText: AppColors.blackColor,
              placeholderText: AppColors.greyColor,
              secondaryText: AppColors.blackColor,
              componentBorder: AppColors.blackColor,
            ),
            shapes: const PaymentSheetShape(
              borderWidth: 4,
              shadow: PaymentSheetShadowParams(color: AppColors.blackColor),
            ),
            primaryButton: PaymentSheetPrimaryButtonAppearance(
              shapes: const PaymentSheetPrimaryButtonShape(blurRadius: 8),
              colors: PaymentSheetPrimaryButtonTheme(
                light: PaymentSheetPrimaryButtonThemeColors(
                  background: AppColors.blueColor,
                  text: AppColors.whiteTextColor,
                  border: AppColors.transparentColor,
                ),
                dark: PaymentSheetPrimaryButtonThemeColors(
                  background: AppColors.blueColor,
                  text: AppColors.whiteTextColor,
                  border: AppColors.transparentColor,
                ),
              ),
            ),
          ),
          //  billingDetails: billingDetails,
        ),
      );

      await presentPaymentSheet(context);
    } catch (e) {
      debugPrint('error => ${e.toString()}');
      state = SuccessResponseState.error(e.toString());
    }
  }

**Comment by nayanbabariya** [comment]
@atulproject99 How you've enabled the `Apple Pay` button in the stripe payment sheet? because I've also added this snippet:

```dart
applePay: const PaymentSheetApplePay(
          merchantCountryCode: 'GB', buttonType: PlatformButtonType.pay),
```

I've also enabled the Apply Pay option from the Stripe dashboard. however, I've not created a merchant ID and created a certificate on Apple developer.

I can see the `Apple Pay` button on the Simulator but not on a real device. Could you guide me to enable the button on the stripe payment sheet?

**Comment by nayanbabariya** [comment]
@atulproject99 I've resolved it now. the issue was I did not register the merchant identifier on Apple developer and certificate on the Stripe payment method. that is required. I was under the assumption that the Stripe sheet itself is managing it.
These are the things that we need to ensure before seeing the `Apple Pay` button on a real device.

✅ Merchant registration and upload certificate on the Stripe dashboard by enabling Apple Pay
✅ Enable the capabilities `Apple Pay` from Xcode and add the merchant ID.
✅ Apple's Sandbox account with the country where Apple Pay is supported
✅ The device should logged in with this sandbox account Apple ID
✅ In the Wallet, there should be a card with Apple Pay ready.

If you pass all the above checks then I hope we are good to go 🚀🚀

**Comment by remonh87** [comment]
yes for clarity make sure to follow the instruction set here: https://docs.page/flutter-stripe/flutter_stripe/sheet#6-optional---enable-apple-pay-only-ios

**Comment by nayanbabariya** [comment]
@remonh87 The actual issue is different. please try to have a look.

**Comment by remonh87** [comment]
@nayanbabariya  the issue is different but it is the same cause apple will only open the sheet on a real device when things are properly configured. We have no control over the behavior of the apple sheet.

@atulproject99  I would recommend also looking at the xcode logs because this may give you a clue

**Comment by nayanbabariya** [comment]
Okay @remonh87 Got it, thanks.

**Comment by hamza1772** [comment]
I was able to resolve this error. The problem was that I was using the app name in the Stripe.merchantIdentifier field, but instead, we should use the Merchant ID created in the Apple Developer account. I resolved this by inserting the following lines in the main.dart file:

```
  Stripe.publishableKey = GlobalValues.stripePublishableKey;
  Stripe.merchantIdentifier = "merchant.com.example.app";
  await Stripe.instance.applySettings();
```

Make sure to follow instructions from this link [https://docs.page/flutter-stripe/flutter_stripe/sheet#6-optional---enable-apple-pay-only-ios](url) very carefully as @remonh87 suggested us.
