### ISSUE TITLE
Windows and Linux support

### ISSUE THREAD

**Issue by mregnauld** [flutter-stripe/flutter_stripe#1920]
I’m currently working on a Flutter app, available on Android, iOS, macOS, Windows and soon Linux.

**Describe the solution you'd like**
I would like a native support of Stripe for Flutter for both Windows and Linux.

**Describe alternatives you've considered**
No serious alternative yet. The only one I'm thinking of is asking my users to download my app on their phones and pay from their phones, then sync with the app on Windows / Linux. That's quite a lot of steps...

**Comment by remonh87** [comment]
Thank you for reaching out. Unfortunately Stripe does not have a native sdk for linux and windows that we can use.  We need to use their elements because else the library needs to be PCI compliant at the highest level which is difficult to achieve.  I would recommend going for either a web element that you host or even better stripe checkout: https://docs.stripe.com/payments/checkout
