### ISSUE TITLE
Add callback for Payment Failures

### ISSUE THREAD

**Issue by pcba-dev** [flutter-stripe/flutter_stripe#1927]
**Is your feature request related to a problem? (please describe)**
I would like to see better handling of payment intent failures in the current implementation of the Payment Sheet. At the moment, the Payment Sheet does not provide a callback to handle payment failures such as incorrect card details, wrong CVC, or insufficient funds. While Stripe sends a `payment_failed` event to the webhook, there is no way to capture this failure within the Flutter client to notify users with an appropriate message apart from the errors shown by this plugin.

**Describe the solution you'd like**
It would be great to have a callback, such as `onPaymentFailed`, that triggers whenever a payment intent fails with status `payment_failed`. This would allow developers to retrieve failure information and display meaningful error messages to users in real time, improving user experience during payment processing.

**Describe alternatives you've considered**
?

**Additional context**
The Stripe API already sends a `payment_failed` event to the webhook. Exposing this failure event in the Flutter client would streamline error handling and improve user interaction with the payment flow.

**Comment by remonh87** [comment]
There is no need for this functionality because the paymentsheet itself provides localised error messages in the element itself to the user. Also there are 2 types of stripe errors:

- Client side (something goes wrong on the phone itself) we will throw a Stripeexception that contains a localised error message that you can use coming from the stripe sdk.
- Server side (something goes wrong handling the payment because of fraud detection, bank due dilligence etc). This you receive at the server and we never receive this error client side. 
 
It is a good practice to always check at your own backend if the payment is successful and provide an error message yourself. The flutter sdk is only for collecting payment info but the fact that this completes does not guarantee the payment is accepted. Hope this helps :)
