### ISSUE TITLE
confirmSetupIntent error on iOS

### ISSUE THREAD

**Issue by romme86** [flutter-stripe/flutter_stripe#204]
**Describe the bug**
Using the example in setup_future_payment_screen.dart
I set up a simple card saving procedure with the CardField widget, this is working for Android but not for Apple.

**To Reproduce**
1. set up the CardField
2. do a request to get back the client_secret
3. call confirmSetupIntent() with the client_secret
4. this will give an error on the .g file: "[]id was called on null"

This is the code giving the error.

```
// 3. Confirm setup intent
  final setupIntentResult = await Stripe.instance.confirmSetupIntent(
    clientSecret,
    PaymentMethodParams.card(
       billingDetails: billingDetails,
    ), {}
  ).catchError((error) {
  debugPrint('Setup Intent confirmed $error');
});
```

we use it to have the paymentMethodIdBack: `setupIntentResult.paymentMethodId`

On Android the same procedure is working fine

**Expected behavior**
after the confirmSetupIntent() the 3DS procedure is triggered if needed and the card is saved on stripe.

**Smartphone / tablet**
 - Device: emulator iphone 12 pro max - and real device iphone 12 / iphone 11
 - OS: iOS last
 - Package version:  -
 - Flutter version environment:
      sdk: ">=2.10.0 <3.0.0"

**Additional context**
-

**Comment by remonh87** [comment]
Did you test it with the latest version on master. I fixed the example screen yesterday since there was indeed a bug in it. 

I did the following on iOS:
1.  Enter card `4000000000003063` in the card field (stripe test card containing 3d secure).
2.  press `save` , this is succesfull
3.  Press `pay with saved card off session` I get an error response (still correct since I need to authorize payment using 3d secure).
4.  Press `recovery flow` then the payment is successfull

I will close it for now but feel free to reopen if you still encounter issues.

**Comment by romme86** [comment]
I tried pulling your changes and running the example but it does not start now:

    lib/screens/payment_sheet_screen.dart:87:31: Error: Type 'PaymentSheetResult' not found.
      String _createResultMessage(PaymentSheetResult result) {
                                  ^^^^^^^^^^^^^^^^^^
    lib/screens/payment_sheet_screen.dart:87:31: Error: 'PaymentSheetResult' isn't a type.
      String _createResultMessage(PaymentSheetResult result) {
                                  ^^^^^^^^^^^^^^^^^^
    lib/screens/payment_sheet_screen.dart:108:46: Error: This expression has type 'void' and can't be used.
              content: Text(_createResultMessage(result)),

gives this error

**Comment by remonh87** [comment]
Please check  https://github.com/flutter-stripe/flutter_stripe#setup and follow the instructions
