### ISSUE TITLE
CardField data not updating

### ISSUE THREAD

**Issue by kwstasarva** [flutter-stripe/flutter_stripe#242]
**Describe the bug**
I am trying to edit the card details through the CardField widget but no matter what I type, the card field does not update.

**To Reproduce**
1. Clone the repo and run the example
2. Enter any number in a selected card field

**Expected behavior**
The card field should update and the onCardChanged method should get triggered.

**Smartphone**
 - Device: [iPhone 12 Pro Max]
 - Package version: [commit: df2f9c1]
 - Flutter version [2.0.3]

**Comment by jonasbark** [comment]
@jamesblasco can you please have a look?

**Comment by kwstasarva** [comment]
I've discovered that this happens only when "Connect hardware keyboard" is enabled. So basically if you disable that, you can type normally in the field by using the on screen keyboard. command+shift+k is the command to enable/disable the hardware keyboard while focusing the simulator window. Hope this helps

**Comment by jamesblasco** [comment]
@kwstasarva indeed this only happens in the simulator when using the macOS keyboard instead of the one from the iOS simulator. 

I wonder if this problem happens also with an iPad Pro with an attached keyboard. If anyone has one and could try it would be awesome 🙂

I will close the issue here as it looks like it is a problem with Flutter and native text input fields. I Will try to make an example code with the error and submit an issue in the Flutter repo, but as it does not affect apps in productions it is not a priority
