### ISSUE TITLE
Can i create a custom ui made from flutter widgets, if so from where can i find the docs? if not can i just use the nodejs sdk and send all the required details there and perform the whole logic there. also how can i capture PayPal payments

### ISSUE THREAD

**Issue by NeatFastro** [flutter-stripe/flutter_stripe#283]
**Is your feature request related to a problem? (please describe)**
A clear and concise description of what the problem is. Ex. I would like to see [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear description of  alternative solutions or features you've considered.

**Additional context**

**Comment by remonh87** [comment]
- Stripe doesn't integrate with PayPal so no.
-  You can use a custom UI by using: https://github.com/flutter-stripe/flutter_stripe/blob/0ee2bf30613fb5cacde7efc25e80851f93044df1/packages/stripe/lib/src/stripe.dart#L325 .  However we advice strongly against this since you need to be PCI compliant which is quite a lot.
