### ISSUE TITLE
SetupPaymentSheetParameters options 

### ISSUE THREAD

**Issue by naumanahmed19** [flutter-stripe/flutter_stripe#303]
Hi,

Not sure if it's a bug or I am missing something. some of the options for `SetupPaymentSheetParameters` are not working for me.

I have
`testEnv: false `but still, I can make payment using a dummy card (4242 4242 4242 4242)
`merchantDisplayName ` is not displaying anywhere on the sheet.
`style`: is not working with theme switch ( I saw a bug report about this already)

```
   await Stripe.instance.initPaymentSheet(
        paymentSheetParameters: SetupPaymentSheetParameters(
          applePay: false,
          googlePay: false,
          style: ThemeMode.dark,
          testEnv: false,
          merchantCountryCode: 'DE',
          merchantDisplayName: 'XYZ',
          customerId: _paymentSheetData['customer'],
          paymentIntentClientSecret: _paymentSheetData['paymentIntent'],
          customerEphemeralKeySecret: _paymentSheetData['ephemeralKey'],
        ),
      );
``

**Comment by jamesblasco** [comment]
- testEnv is used only for Google Pay. Probably you can use the 4242 car because are using the test publishing key.
- `merchantDisplayName`. You can see it displayed at the bottom, `Save this card for future payments with ...`
- `style` is only available for iOS at the moment and it is not responsive. Once initPaymentSheet is called with the correspondent param it won't change if the app theme is changed

<img width="683" alt="Screenshot 2021-08-30 at 09 15 24" src="https://user-images.githubusercontent.com/19904063/131300500-5e408e46-f84a-418a-b29d-a84f410486bf.png">

**Comment by naumanahmed19** [comment]
Thank you for responding I think you are right maybe it's because of the test publishing key.
