### ISSUE TITLE
Question: how to retrieve payment  method id when using presentPaymentSheet method?

### ISSUE THREAD

**Issue by mrRedSun** [flutter-stripe/flutter_stripe#319]
Web SDK allows to retrieve it, it's a little weird that mobile SDK just returns void and handles errors with exceptions.

**Comment by remonh87** [comment]
The payment sheet is just a way of collecting data regarding the payment in order to confirm a payment or store it in order to charge it later. In case we return void it is successful else we throw indeed an exception. The stripe native sdk doesn't provide us with data at the moment so that is why we do not show it.
