### ISSUE TITLE
Stripe Terminal SDK Intergration

### ISSUE THREAD

**Issue by trof-app** [flutter-stripe/flutter_stripe#39]
Would it be possible to include the terminal SDK into this new project, there is a andriod and iOS SDK available from stripe but no flutter implementation that I can find currently.

There is a growing use case for accepting in person payments via stripe as well as online payments
https://stripe.com/docs/terminal

**Comment by jamesblasco** [comment]
Hello there, there are no current plans to include support for the Stripe Terminal SDK now. We are working on making this package stable and publishing publicly.

We will this issue open to track the demand. Depending on that we might consider it to support it in the future

**Comment by emmett-deen** [comment]
Revisiting this, my team will need terminal support for an upcoming project. Has priority been changed on this or are there still no plans?

**Comment by rachonzedev** [comment]
any news ?

**Comment by ccfiel** [comment]
any update on this?

**Comment by atdrive-github** [comment]
any update on this?

**Comment by remonh87** [comment]
We are in contact with Stripe to deliver us some base on which we can start. We will let you know when there are developments on this front.

**Comment by doshikh** [comment]
Any update on this ?

**Comment by johnettPhenomtec** [comment]
We also need to use Stripe Terminal SDK(flutter) in one of our projects.

**Comment by Yahllil** [comment]
Any news?

**Comment by ishaq007** [comment]
Any update here ?

**Comment by jonasbark** [comment]
Please refrain from asking about status updates - we will update this ticket as soon as there are news :)

**Comment by Yahllil** [comment]
I ended up implementing it myself in my project. If anyone needs help with it feel free to contact me

**Comment by johnettPhenomtec** [comment]
@Yahllil  can you share the repository(not the project but the implementation part)?

**Comment by Yahllil** [comment]
@johnettPhenomtec Unfortunately I can't share the code, becuase my clients has the rights for the code.
But if you have any question regarding the implementation I'll be happy to help

**Comment by johnettPhenomtec** [comment]
@Yahllil I understand.

**Comment by AmanCodibex** [comment]
@Yahllil,
So I am trying to implement the SDK in Flutter, but I am having issues while connecting the reader (Simulated Reader). It is giving the following error: "Terminal is currently only available in certain countries. For more information, see https://stripe.com/docs/terminal."

I have set up my emulator's location to be in Canada which is a supported country, but anyway I am using a simulated reader that does not really have to be bounded by a location. So I am not able to understand the issue here?

Can you please help with the same?

**Comment by Yahllil** [comment]
> @Yahllil, So I am trying to implement the SDK in Flutter, but I am having issues while connecting the reader (Simulated Reader). It is giving the following error: "Terminal is currently only available in certain countries. For more information, see https://stripe.com/docs/terminal."
> 
> I have set up my emulator's location to be in Canada which is a supported country, but anyway I am using a simulated reader that does not really have to be bounded by a location. So I am not able to understand the issue here?
> 
> Can you please help with the same?

I'd be happy to help, but I did not experience any issue regarding the location. Have you been able to solve it?

**Comment by AmanCodibex** [comment]
> > @Yahllil, So I am trying to implement the SDK in Flutter, but I am having issues while connecting the reader (Simulated Reader). It is giving the following error: "Terminal is currently only available in certain countries. For more information, see https://stripe.com/docs/terminal."
> > I have set up my emulator's location to be in Canada which is a supported country, but anyway I am using a simulated reader that does not really have to be bounded by a location. So I am not able to understand the issue here?
> > Can you please help with the same?
> 
> I'd be happy to help, but I did not experience any issue regarding the location. Have you been able to solve it?

Yeah, the problem was the key that I was using. It needs to be from a Stripe Account which has a region supported by Terminal. I was using an Indian Account's key which is why it was causing the issue. After using the key from a supported region's account, it connected perfectly.

**Comment by awazgyawali** [comment]
@remonh87 I need terminal SDK on one of my project. I am actually good at writing flutter plugins that touches native android and iOS SDK. 

Regardless of the possibility that flutter_stripe will add the support, I must write the plugin.

Therefore, the question here is, if you guys have the plan include terminal SDK on this plugin, I will send a PR that can do so here or I am willing to release another `flutter_stripe_terminal` with the feature.

Let me know the plan for the feature and then we can collaborate accordingly if needed.

**Comment by doshikh** [comment]
Hi @awazgyawali - if you have already written plugin you should release it. I have also write the same in my project but not separated as plugin but it must needed.

**Comment by awazgyawali** [comment]
Hey everybody, I have released very early version of the terminal SDK for flutter.

It's pretty simple and straight forward and get the job done. Note that I have not tested for every kind of readers out there as I don't have them all however I have verified them on simulated setup.

Currently supported features:
- Initializing terminal SDK
- Scanning the readers
- Connecting to a device (Only bluetooth devices on android)
- Checking connection status
- Checking connected device
- Read payment method from the device

Currently unsupported features(because I didn't needed it at the moment.):
- Create payment intent
- Process payment
- Capture payment


Please feel free to send a PR for further feature as you need or just create an issue on the repo with the feature request. I have no plans to maintain this repo in the long future thus the package will be deprecated as soon as flutter_stripe adds support to their SDK as mentioned [here](https://github.com/flutter-stripe/flutter_stripe/issues/39#issuecomment-1084191165) 

Github Repo Link: https://github.com/awazgyawali/flutter_stripe_terminal
Pub Link: https://pub.dev/packages/stripe_terminal

Please consider buying me a coffee if you can:

[!["Buy Me A Coffee"](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png)](https://www.buymeacoffee.com/gbraad)

**Comment by safwanidrees** [comment]
> Hi @awazgyawali - we are planning to add a plugin for Stripe Terminal for Flutter. We will update this thread once we can share a timeline.

Any Update?

**Comment by rafinjos** [comment]
To any developr can integrate in person payment from stripe in flutter.? I have a restaurant mobile kiosk, only remain the payment in perzon from stripe to integrate BBPos  skype  rafael.torres.centeno  1-863-604-6313 WHATAPP

**Comment by shkvoretz** [comment]
Yeah, it would be really cool to have this support in the official package

**Comment by Yahllil** [comment]
Will Stripe Terminal's Tap to Pay on iPhone will be supported in this package?

**Comment by awazgyawali** [comment]
Yes

**Comment by nick-happsnow** [comment]
Any update on when Stripe Terminal will be supported? @jamesblasco

**Comment by remonh87** [comment]
We hope to give an update this the coming month(s).

**Comment by ReceiptlyNZ** [comment]
Any word on this yet? :)

**Comment by hareshgediya** [comment]
Any update regarding Stripe Terminal SDK?

**Comment by remonh87** [comment]
We would love to work on it but as maintainers we lack the bandwidth to properly maintain it at the moment. It is a huge sdk, implementing it is one thing but we also need to provide proper support. I think for now this is low on the list as we prefer to focus on keeping up to date with Android, iOS sdk releases and providing a stable web sdk.

CC: @jonasbark  @jamesblasco

**Comment by mrgithub** [comment]
I am also looking to implement stripe tap to pay with stripe using flutter - any official news?

**Comment by mrgithub** [comment]
> Hi @awazgyawali - we are planning to add a plugin for Stripe Terminal for Flutter. We will update this thread once we can share a timeline.

Has this moved forward? We need official support and tap to pay would be excellent!

**Comment by batuhanseckinnnn** [comment]
Are there any changes? We need this development.

**Comment by remonh87** [comment]
Me and @jonasbark had a good discussion about it and we decided to not develop this functionality for Flutter. Reason is that the maintenance of huge SDK like Stripe on 3 platforms  cost us a lot of time.  We do the maintenance in our free time and we have no capacity to also maintain a terminal integration. We encourage the community to create an integration themselves and we are happy to lend some of our expertise on this.
