### ISSUE TITLE
CardFormField not showing and throwing exception on flutter_stripe 2.0.0, flutter 2.5.2, android

### ISSUE THREAD

**Issue by ehcpdeveloper** [flutter-stripe/flutter_stripe#393]
Using:
flutter_stripe: ^2.0.0
flutter 2.5.2
ext.kotlin_version = '1.4.32'
Android

CardFormField not showing and throwing exception below. 
I have also tried with other versions of kotlin in build.gradle. 

Same config works normal on ios. The problem is only on Android.

On the same config, working with (both android+ios):
import 'package:stripe_sdk/stripe_sdk_ui.dart';
CardForm(formKey: formKey, card: card),

`E/MethodChannel#flutter/platform_views(17005): Failed to handle method call
E/MethodChannel#flutter/platform_views(17005): kotlin.UninitializedPropertyAccessException: lateinit property stripeSdk has not been initialized
E/MethodChannel#flutter/platform_views(17005): 	at com.flutter.stripe.StripeAndroidPlugin.getStripeSdk(StripeAndroidPlugin.kt:31)
E/MethodChannel#flutter/platform_views(17005): 	at com.flutter.stripe.StripeAndroidPlugin$onAttachedToEngine$2.invoke(StripeAndroidPlugin.kt:53)
E/MethodChannel#flutter/platform_views(17005): 	at com.flutter.stripe.StripeAndroidPlugin$onAttachedToEngine$2.invoke(StripeAndroidPlugin.kt:25)
E/MethodChannel#flutter/platform_views(17005): 	at com.facebook.react.uimanager.ThemedReactContext.getNativeModule(ThemedReactContext.kt:17)
E/MethodChannel#flutter/platform_views(17005): 	at com.reactnativestripesdk.CardFormViewManager.createViewInstance(CardFormViewManager.kt:55)
E/MethodChannel#flutter/platform_views(17005): 	at com.flutter.stripe.StripeSdkCardFormPlatformView.<init>(StripeSdkCardFormPlatformView.kt:33)
E/MethodChannel#flutter/platform_views(17005): 	at com.flutter.stripe.StripeSdkCardFormPlatformViewFactory.create(StripeSdkCardFormPlatformViewFactory.kt:22)
E/MethodChannel#flutter/platform_views(17005): 	at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:151)
E/MethodChannel#flutter/platform_views(17005): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/MethodChannel#flutter/platform_views(17005): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/MethodChannel#flutter/platform_views(17005): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/platform_views(17005): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#flutter/platform_views(17005): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/MethodChannel#flutter/platform_views(17005): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(17005): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter/platform_views(17005): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#flutter/platform_views(17005): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#flutter/platform_views(17005): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(17005): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter/platform_views(17005): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/flutter (17005): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(error, lateinit property stripeSdk has not been initialized, null, kotlin.UninitializedPropertyAccessException: lateinit property stripeSdk has not been initialized
E/flutter (17005): 	at com.flutter.stripe.StripeAndroidPlugin.getStripeSdk(StripeAndroidPlugin.kt:31)
E/flutter (17005): 	at com.flutter.stripe.StripeAndroidPlugin$onAttachedToEngine$2.invoke(StripeAndroidPlugin.kt:53)
E/flutter (17005): 	at com.flutter.stripe.StripeAndroidPlugin$onAttachedToEngine$2.invoke(StripeAndroidPlugin.kt:25)
E/flutter (17005): 	at com.facebook.react.uimanager.ThemedReactContext.getNativeModule(ThemedReactContext.kt:17)
E/flutter (17005): 	at com.reactnativestripesdk.CardFormViewManager.createViewInstance(CardFormViewManager.kt:55)
E/flutter (17005): 	at com.flutter.stripe.StripeSdkCardFormPlatformView.<init>(StripeSdkCardFormPlatformView.kt:33)
E/flutter (17005): 	at com.flutter.stripe.StripeSdkCardFormPlatformViewFactory.create(StripeSdkCardFormPlatformViewFactory.kt:22)
E/flutter (17005): 	at io.flutter.plugin.platform.PlatformViewsController$1.createAndroidViewForPlatformView(PlatformViewsController.java:151)
E/flutter (17005): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/flutter (17005): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter (17005): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (17005): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/flutter (17005): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/flutter (17005): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (17005): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (17005): 	at android.os.Looper.loop(Looper.java:183)
E/flutter (17005): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/flutter (17005): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (17005): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter (17005): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)`

**Comment by ehcpdeveloper** [comment]
Thanks for helping;
after fulfilling all the requirements at https://github.com/flutter-stripe/flutter_stripe#android  now it is working. 
But, I may say that, so many requirements for this package is not very good in the long term.

**Comment by aris-1** [comment]
Getting the same error, applied all  the requirements at https://github.com/flutter-stripe/flutter_stripe#android, but still not working.
Tried calling applySettings as suggested by jonasbark, but that also gives an error.


Using:
flutter_stripe: ^2.1.0
Flutter  2.8.1
ext.kotlin_version = '1.5.0'


import 'package:flutter_stripe/flutter_stripe.dart';
Stripe.publishableKey = "xxxxxx";
final stripeCardController = CardEditController();

Container(child: CardField(
controller: stripeCardController,
onCardChanged: (card) {
print("onCardChanged1 $card");
},
));

Requirements

Android 5.0 (API level 21) and above
- minSdkVersion 21
Kotlin version 1.5.0 and above: 
-ext.kotlin_version = '1.5.0'
Using a descendant of Theme.AppCompat for your activity
-in values/styles.xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <style name="NormalTheme" parent="Theme.AppCompat.Light.NoActionBar">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>



Using an up-to-date Android gradle build tools version:

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.2'  
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"  
     distributionUrl=https\://services.gradle.org/distributions/gradle-6.7-all.zip

Using FlutterFragmentActivity instead of FlutterActivity in MainActivity.kt:
  import io.flutter.embedding.android.FlutterActivity
  import io.flutter.embedding.android.FlutterFragmentActivity 
class MainActivity: FlutterFragmentActivity() { 
}





E/MethodChannel#flutter/platform_views(14280): Failed to handle method call
E/MethodChannel#flutter/platform_views(14280): kotlin.UninitializedPropertyAccessException: lateinit property stripeSdk has not been initialized
E/MethodChannel#flutter/platform_views(14280): 	at com.flutter.stripe.StripeAndroidPlugin.getStripeSdk(StripeAndroidPlugin.kt:28)
E/MethodChannel#flutter/platform_views(14280): 	at com.flutter.stripe.StripeAndroidPlugin$onAttachedToEngine$1.invoke(StripeAndroidPlugin.kt:51)
E/MethodChannel#flutter/platform_views(14280): 	at com.flutter.stripe.StripeAndroidPlugin$onAttachedToEngine$1.invoke(StripeAndroidPlugin.kt:51)

**Comment by Mahrukh288** [comment]
This is how I resolved my issue.

1- Followed all the 6 steps.
2. called applySettings
3. changed Theme.AppCompat.Light in all  values/styles.xml and Theme.AppCompat.DayNight in all values-night/styles.xml
