### ISSUE TITLE
Example App -- Server error when init payment sheet pressed

### ISSUE THREAD

**Issue by muddi900** [flutter-stripe/flutter_stripe#446]
## Describe the bug
Following is the error from the node.

```
node:26772) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of unde undefined
    at C:\src\flutter_stripe\example\server\build\index.js:482:87
    at step (C:\src\flutter_stripe\example\server\build\index.js:33:23)
    at Object.next (C:\src\flutter_stripe\example\server\build\index.js:14:53)        
    at fulfilled (C:\src\flutter_stripe\example\server\build\index.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

## To Reproduce
Run the app in the android emulator, go to init payment sheet and press the button

## Expected behavior
Initiation of the payment sheet

## Smartphone / tablet

- node version: **v14.16.0**
- yarn version: **1.22.17**

**Comment by cdwangco** [comment]
I also have a server error when the init payment sheet is pressed - I have tried on both an Android emulator and actual Android device.

I followed the steps from the readme, other than setting up the web hooks. When I go to Single Step Payment Sheet and try to Init Payment Sheet it hangs for about a minute and then I get the error:

E/flutter ( 8345): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SocketException: OS Error: Connection timed out, errno = 110, address = 192.168.0.92, port = 42610
E/flutter ( 8345): #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:677:35)
E/flutter ( 8345): #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1680:26)
E/flutter ( 8345): #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
E/flutter ( 8345): #3      Socket._startConnect (dart:io-patch/socket_patch.dart:1891:22)
E/flutter ( 8345): #4      Socket.startConnect (dart:io/socket.dart:738:21)
E/flutter ( 8345): #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2439:18)
E/flutter ( 8345): #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2805:12)
E/flutter ( 8345): #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2810:12)
E/flutter ( 8345): #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2694:12)
E/flutter ( 8345): #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2568:7)
E/flutter ( 8345): #10     IOClient.send (package:http/src/io_client.dart:35:38)
E/flutter ( 8345): #11     BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:38)
E/flutter ( 8345): #12     BaseClient.post (package:http/src/base_client.dart:32:7)
E/flutter ( 8345): #13     post.<anonymous closure> (package:http/http.dart:69:16)
E/flutter ( 8345): #14     _withClient (package:http/http.dart:164:20)
E/flutter ( 8345): #15     post (package:http/http.dart:68:5)
E/flutter ( 8345): #16     _PaymentSheetScreenState._createTestPaymentSheet (package:stripe_example/screens/payment_sheet/payment_sheet_screen.dart:51:28)
E/flutter ( 8345): #17     _PaymentSheetScreenState.initPaymentSheet (package:stripe_example/screens/payment_sheet/payment_sheet_screen.dart:70:26)
E/flutter ( 8345): #18     _LoadingButtonState._loadFuture (package:stripe_example/widgets/loading_button.dart:51:30)
E/flutter ( 8345): #19     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
[log] SocketException: OS Error: Connection timed out, errno = 110, address = 192.168.0.92, port = 42610
E/flutter ( 8345): #20     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
E/flutter ( 8345): #21     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
E/flutter ( 8345): #22     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
E/flutter ( 8345): #23     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
E/flutter ( 8345): #24     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter ( 8345): #25     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:444:20)
E/flutter ( 8345): #26     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
E/flutter ( 8345): #27     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
E/flutter ( 8345): #28     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
E/flutter ( 8345): #29     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
E/flutter ( 8345): #30     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
E/flutter ( 8345): #31     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
E/flutter ( 8345): #32     _rootRunUnary (dart:async/zone.dart:1444:13)
E/flutter ( 8345): #33     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 8345): #34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 8345): #35     _invoke1 (dart:ui/hooks.dart:185:10)
E/flutter ( 8345): #36     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
E/flutter ( 8345): #37     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)
E/flutter ( 8345): 
      SocketException: OS Error: Connection timed out, errno = 110, address = 192.168.0.92, port = 42610
      #0      _NativeSocket.startConnect (dart:io-patch/socket_patch.dart:677:35)
      #1      _RawSocket.startConnect (dart:io-patch/socket_patch.dart:1680:26)
      #2      RawSocket.startConnect (dart:io-patch/socket_patch.dart:27:23)
      #3      Socket._startConnect (dart:io-patch/socket_patch.dart:1891:22)
      #4      Socket.startConnect (dart:io/socket.dart:738:21)
      #5      _ConnectionTarget.connect (dart:_http/http_impl.dart:2439:18)
      #6      _HttpClient._getConnection.connect (dart:_http/http_impl.dart:2805:12)
      #7      _HttpClient._getConnection (dart:_http/http_impl.dart:2810:12)
      #8      _HttpClient._openUrl (dart:_http/http_impl.dart:2694:12)
      #9      _HttpClient.openUrl (dart:_http/http_impl.dart:2568:7)
      #10     IOClient.send (package:http/src/io_client.dart:35:38)
      #11     BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:38)
      #12     BaseClient.post (package:http/src/base_client.dart:32:7)
      #13     post.<anonymous closure> (package:http/http.dart:69:16)
      #14     _withClient (package:http/http.dart:164:20)
      #15     post (package:http/http.dart:68:5)
      #16     _PaymentSheetScreenState._createTestPaymentSheet (package:stripe_example/screens/payment_sheet/payment_sheet_screen.dart:51:28)
      #17     _PaymentSheetScreenState.initPaymentSheet (package:stripe_example/screens/payment_sheet/payment_sheet_screen.dart:70:26)
      #18     _LoadingButtonState._loadFuture (package:stripe_example/widgets/loading_button.dart:51:30)
      #19     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:989:21)
      #20     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:193:24)
      #21     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:608:11)
      #22     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:296:5)
      #23     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:267:7)
      #24     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
      #25     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:444:20)
      #26     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:420:22)
      #27     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:278:11)
      #28     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:374:7)
      #29     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:338:5)
      #30     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:296:7)
      #31     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:279:7)
      #32     _rootRunUnary (dart:async/zone.dart:1444:13)
      #33     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
      #34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
      #35     _invoke1 (dart:ui/hooks.dart:185:10)
      #36     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:293:7)
      #37     _dispatchPointerDataPacket (dart:ui/hooks.dart:98:31)

I'm not sure if it's because my config has:

final kApiUrl = defaultTargetPlatform == TargetPlatform.android
    ? 'http://192.168.0.92:4242'
    : 'http://localhost:4242';

But my debug service listening on ws://127.0.0.1:56262/xLqUaOJxF3o=/ws

**Comment by muddi900** [comment]
Yeah if you are using android, you have to enter your dev computers local ip in `config.dart`.

**Comment by fernan542** [comment]
Agreed about this extension needs better documentation. They just put **WHAT TO USE** but skip the part **HOW TO USE**. I'm saying this because I'm new in payment modules and having hard time to study this part in Flutter.

**Comment by jamesblasco** [comment]
The example app was designed to run by default on the simulator with a local server. I will update the readme for the example to explain better that.

Flutter implementation is very similar to ReactNative implementation, so I would recommend you to check the official documentation until we have something similar. The Stripe SDK is quite extensive and with lots of use cases, so it can be hard to maintain but we will try to publish some guides for the most common cases soon.

For the payment sheet I would recommend to read this guide
https://stripe.com/docs/payments/accept-a-payment

**Comment by jamesblasco** [comment]
While debugging one of the maintainers changed the default IP address to his local one, I will revert this change so it works as expected.

**Comment by Jepablo** [comment]
I swear to god github answer are THE WORST!
