### ISSUE TITLE
Extremely poor communication

### ISSUE THREAD

**Issue by k-ane** [flutter-stripe/flutter_stripe#458]
I realise that this is a community maintained package, but it is the closet thing to an official Stripe Flutter package we have. Stripe even officially contributed $21,000 to the project, yet it's impossible to get in touch with the maintainers.

I realise you can't always solve issues right away, but acknowledgement and communication is important.

Going weeks without even a "thanks for this, we're working on it, or a "sorry this isn't on our roadmap in the near future" is extremely frustrating.

The worst part is when you come back thinking maybe they have just been busy, but you see responses on issues newer than yours.

So @jonasbark @remonh87 @jamesblasco please take one hour or so to go through the 50 or so open issues, and just communicate in some way with each issue people have taken the time to report

Sorry for the negativity,
Cheers

**Comment by remonh87** [comment]
@k-ane  I am sorry you feel this way and I am trying to understand where this come from. Can you mention specific issues where we dropped the ball (only I can think of is web support?. In general we react quite quick on issues but I realise last week due to other obligations it was a bit more difficult. Also  to put things in perspective:

- 16 of them are blocked because they are related to a bug or a feature request in one of the Stripe native sdks or an issue in Flutter related to platform views, they are also labeled as blocked. 
- Besides the 50 open issues we closed more then 257 issues. 
- We have a monthly release cycle and are up to date with the Stripe native sdk. 
 
Thanks for your honesty but I also hope you understand  that maintaining an open source library is not always easy and we really are working hard to create the best Flutter Stripe integration possible.

**Comment by k-ane** [comment]
@remonh87 I really appreciate you getting back to me and once again, sorry for the negative tone.

[The issue I submitted is this one here](https://github.com/flutter-stripe/flutter_stripe/issues/439)

I submitted it under my work account. It pertains to AUBecsDebit integration, I have not been able to reconcile the Stripe documentation with the available methods as of yet, so if you can help me out with it that would be amazing :)

I appreciate how difficult it must be to manage a project of this scale, there were a couple of other issues I noticed which were not yet responded to as well, but I did not mean to down play the massive contribution you are all making to the Flutter ecosystem.

For the issue listed about, please let me know if there is any more information I can provide.

Cheers,
Kane
