### ISSUE TITLE
How to go from the test to live? Do I need to host a server like the nodejs example?

### ISSUE THREAD

**Issue by niyonx** [flutter-stripe/flutter_stripe#473]
**Is your feature request related to a problem? (please describe)**
Improvement to documentation: I would like to see more documentation of how to go from test to live from the example with a nodejs server

**Describe the solution you'd like**
Some questions which are not obvious to me:
- is switching the keys enough?
- should i host the yarn server even when using the live keys?
- can I use the live keys without the yarn server?
- the amount to be charged in the example is 10.99, how do I change the amount from the flutter side?

**Comment by remonh87** [comment]
is switching the keys enough?

- you need to replace your test keys with production keys. You also need to add the production publishable key to your app set test mode to false in case you use the payment sheet.

should i host the yarn server even when using the live keys?

- Your backend needs to be reachable for the app that you are using so test you need to host it.

can I use the live keys without the yarn server?

-  you always need a backend because the backend is responsible for creating the payment intents. Depending on the payment methods that you provide you should check the stripe docs on what to implement server side. Our library only handles the client side.

the amount to be charged in the example is 10.99, how do I change the amount from the flutter side?

-  You can't and that would be security wise very bad. What you need to do is request a new payment intent (with the new charge)  in case the amount is wrong. Your backend needs to handle this with Stripe.

Hope this helps.

**Comment by niyonx** [comment]
Thanks Remon,

- Where do I set test mode to false?
- My backend is in dart, it's good now. I was able to replicate the node.js backend with the stripe rest api. I am requesting a payment intent with the charge I need as well.

**Comment by remonh87** [comment]
if you use the payment sheet we have a boolean that you can set . For the rest everything goes automatic because you use the production keys

**Comment by federico2390** [comment]
@niyonx do you have an example of the backend in dart please?

**Comment by niyonx** [comment]
hey @federico2390 I had to use the call the REST API to replace the node js backend. Many of the functions are not built-in
