### ISSUE TITLE
Staying PCI Compliant using this package

### ISSUE THREAD

**Issue by vinnytwice** [flutter-stripe/flutter_stripe#504]
I'm integrating Stripe as the payment gateway an I'm looking at your `flutter_stripe` package as it says on the tin

>Simplified Security: We make it simple for you to collect sensitive data such as credit card numbers and remain PCI compliant. This means the sensitive data is sent directly to Stripe instead of passing through your server. For more information, see our Integration Security Guide.

So I was expecting an integration to call Stripe sdk directly as I do in my Nodejs server where I create the `PaymentIntent` as mentioned in Stripe custom flow guide

>Create a PaymentIntent
Add an endpoint on your server that creates a PaymentIntent. A PaymentIntent tracks the customer’s payment lifecycle, keeping track of any failed payment attempts and ensuring the customer is only charged once. Return the PaymentIntent’s client secret in the response to finish the payment on the client. (server)

>Use Stripe.js to remain PCI compliant by ensuring that payment details are sent directly to Stripe without hitting your server. (client) 

and confirm that `PaymentIntent` in my flutter app without hitting my server.

I was expecting to find in `flutter_stipe` API the equivalent of the Stripe node sdk 
```
const paymentIntent = await stripe.paymentIntents.confirm(
  'pi_1EUq4543klKuxW9fVKimzjFV',
  {payment_method: 'pm_card_visa'}
);
```
but I found only the method
```
Future<PaymentIntent> confirmPayment( String paymentIntentClientSecret,PaymentMethodParams data,[ Map<String, String> options = const {},])
```
which does

>Confirms a payment method, using the provided paymentIntentClientSecret and data.
See PaymentMethodParams for more details. The method returns a PaymentIntent. Throws a StripeException when confirming the paymentmethod fails

I see from your example app that you hit a server to register customers cards etc, but doesn't it make the PCI Compliance go down the drain right?.

https://github.com/flutter-stripe/flutter_stripe/blob/main/example/server/src/index.ts

I'm sure I'm not understanding the package but your API `confirmPayment` just ads the paymentMethod to the `PaymentIntent` right?. So ho do you confirm `PaymentIntent`s?

My whole flow idea ( basically mimicking Stripe's custom flow )  is:

1. `Client` app (Customer) sends an order to `Server`. 
2. `Server` checks availability of order's products (extra step I take to avoid issuing refunds)  and create a `PaymentIntent` which gets returned to `Client` with the (eventually) corrected Order. 
3. `Client` confirms `PaymentIntent` received in step 2. 
4. `Server` captures the `PaymentIntent` and actually modified the db for products quantities ad created the Order record. 
5. When the `Client` confirms receiving the Order it `Server` makes the PayOut the `PaymentIntent` so money gets transferred to merchant (Account).

Any explanation will be very helpful. 
Cheers

**Comment by remonh87** [comment]
@vinnytwice  

Not sure what you mean with "The server register customer cards" since we do not send any card data to the backend server in our library. I think the example server creates a customer using the Stripe API but that is it.   You can use your flow following: https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/payment_sheet/payment_sheet_screen.dart .

In general it is sth like:

1. Client app creates order on the server
2. Server creates an payment intent on Stripe and provides the `paymentintentId` and optional a customer id + ephermal key (so you can save the cards). 
3. Customer fills in payment details on the client and confirms the payment.
4. Server receives a callback from Stripe whether or not payment is succeeded
5. Server informs the client payment is success

Regarding PCI compliance: you always need to make sure your organisation is PCI compliant (see the Stripe dashboard). The advantage of our library is that we use native Stripe components and do not process anything on the Flutter side. This allows you to comply to the less strict PCI compliance regulations (just fill in a self-assessment).

Hope this helps

**Comment by vinnytwice** [comment]
@remonh87 thence you very much for the exhausting explanation. I'm still wrapping my head around some concepts I guess, hence my confusion with your API.

**Comment by vinnytwice** [comment]
@remonh87 Sorry to bother you again , but I didn't quite get  a few things from your answer above.

>Client app creates order on the server

Ok, that's how I do it.

>Server creates a payment intent on Stripe and provides the paymentintentId and optional a customer id + ephermal key (so you can save the cards).

Ok, I do return to client a PaymentIntent that he can confirm in app, but can you please elaborate about the ephemeral key and how to use it??

Other doubts I still have:

1. Does this package interact with Stripe directly or I have to pass cards details to my server which communicated the to Stripe? 
The ephemeral key from above makes me think the latter, but looking at package initialisation `Stripe.publishableKey = stripePublishableKey;`makes me think the first.

In case the answer is no( I need to pass cards details to my server, then to Stripe) why should the package be initialised at all??

From the `createPaymentMethod` method I read
>Converts payment information defined in data into a PaymentMethod object that can be passed to your server, so again I think I need to use my server to manage users' cards etc etc..so again why instantiate the package at all?

Sorry for the bothering again, and many thanks..
