### ISSUE TITLE
Invoice Issue with saved cards

### ISSUE THREAD

**Issue by PrinzKenny1** [flutter-stripe/flutter_stripe#585]
### Discussed in https://github.com/flutter-stripe/flutter_stripe/discussions/542

**Comment by remonh87** [comment]
I did some studying about invoices in the[ stripe docs ](https://stripe.com/docs/billing/subscriptions/overview#how-payments-work-subscriptions) and I think you need to use  https://github.com/flutter-stripe/flutter_stripe/blob/40e9073bdc7b822c7881d190cbca79a8f8d26a48/packages/stripe/lib/src/stripe.dart#L235 . 

Probably the card has some 3d secure stuff. What I also understood from the docs is that Stripe recommends using `setupintents` if you want to collect payment data without charging them directly. 

I would suggest to try this or else contact Stripes support to help you further because it looks like our library is able to handle invoices and subscriptions. I will close this issue for now feel free to reopen it when there  is still an issue. Also I will create another ticket to document subscriptions because it is a more advanced scenario then a normal payment
