### ISSUE TITLE
How to remove unused code for ios?

### ISSUE THREAD

**Issue by SI-IC** [flutter-stripe/flutter_stripe#603]
Hi everybody!

**Describe the bug**
I use this package for apple pay and android pay through stripe only. After publish my app to appstore connect, I've got email from them:
<img width="1328" alt="Screenshot 2022-02-28 at 12 13 16" src="https://user-images.githubusercontent.com/78099231/155956224-b1d9bbb8-4e9d-46a5-b599-f85e50e1dd14.png">

The fact is that I don't use scan card possibility and notifications in my app.
So how to remove from building unnecessary code to successfully publish my app?   

**To Reproduce**
Use only apple pay in app.

**Expected behavior**
Build contains only used code.

**Smartphone / tablet**
Any iOS device.

Thank you in advance.

**Comment by remonh87** [comment]
This is part of the native iOS Stripe SDK (part of the payment sheet implementation). What you can do is just add the following to info.plist: `We do not use your camera`. 

Regarding the notifications I am not sure this is related to our sdk since we do not use notification. Can it be another library that you are using?

**Comment by SI-IC** [comment]
> remonh87

Thanx a lot, I'll try it.
