### ISSUE TITLE
Error not recorded on 3ds2 cards if i click on back button instantly.

### ISSUE THREAD

**Issue by kawaldeep2507** [flutter-stripe/flutter_stripe#605]
**Describe the bug**
Error not recorded on 3ds2 cards if i quits the process instantly. This is happening on most of the 3d secure 2 test cards only. i tired with "4000000000003220" &  "4000000000003238". My app gets struck on loading because it didn't received any intent result.(neither success nor error report). Tried with try/catch & (onError & catchError) also but did received any. 

**To Reproduce**
1. Created a customer from backend.
2. Created a setupIntent.
3. Confirm a setupIntent. Press back button as soon you see "Processing" on page.

Scenario 2
1. Created a customer from backend.
2. Created a createPaymentMethod.
3. Create a paymentIntent from backend provinding them your customerId & paymentMethodId.
4. Confirm a confirmPayment. Press back button as soon you see "Processing" on page.

**Expected behavior**

**Smartphone**
 - Device: Oneplus 5t & Oneplus 7
 - OS: [Android 10, Android 11]
 - Package version: [

Stripe 2.2.0]
 - Flutter version [2.8.1.]

**Additional context**
Here are 2 videos showing what i mean. In one video if i wait for few seconds and then clicks on back button. i received an error log in OnError block. 
In Other video if i click on back button as soon as i see "Processing" i didn't received any  error log.

https://user-images.githubusercontent.com/66901420/156038886-08e2fa24-9d55-425f-94c3-a359be0c3067.mov

https://user-images.githubusercontent.com/66901420/156037563-2736f191-5797-444e-b5cf-862a09e33149.mov

**Comment by remonh87** [comment]
I can reproduce this as well, unfortunately there is nothing we can do about this since these are test verification screens made by stripe and run outside Flutter,.  I see two ways of solving it:
1. You need to check with your backend if the PaymentIntent is successfully processed. This is also recommended practice anyway.  You can add a [lifecycleobserver](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver-class.html) to your widget and when you come back (which is done by the back press) you can start polling your backend if the payment is successful. If not after x amount of time you raise an error.

2. Use the paymentsheet instead of the card field. I couldn't reproduce the issue on that component, since the paymentsheet is a full native android activity. The paymentsheet has superior ux in our opinion at the cost of a bit of branding. 

Hope this helps.
