### ISSUE TITLE
Unrecognised app. Please make sure that you trust this in Google Pay 

### ISSUE THREAD

**Issue by ravilimbani2203** [flutter-stripe/flutter_stripe#655]
**Describe the bug**
I try google pay with stripe its shows continues error like 

**Unrecognised app. Please make sure that you trust this app before proecessing**

 - flutter_stripe: ^2.3.0
 - Flutter version [2.8.1]

I complete google pay business console setup and also set merchant id in google_pay.json file
Here is my json file

![Screen Shot 2022-03-25 at 10 22 22 AM](https://user-images.githubusercontent.com/87609109/160056715-de0c4ab1-a03e-49c3-9ea5-fea49f232f2a.png)

**Comment by remonh87** [comment]
This is an official error coming from[ Google Pay](https://developers.google.com/pay/api/android/support/troubleshooting#unrecognized-app).   I think you probably use stripe test keys combined with a production json file which is a mismatch.  I would also check: 
https://developers.google.com/pay/api/android/guides/test-and-deploy/integration-checklist . 

I will close it for now because this is not sth we can solve in our code but feel free to ask another question / issue  in case you run into some troubles with our plugin
