### ISSUE TITLE
Stripe Connect Express Onboarding and Functionality

### ISSUE THREAD

**Issue by LentNow** [flutter-stripe/flutter_stripe#679]
I would like to see a stripe connect express or custom account functional with Flutter. 

Specifically, the onboarding and payment functionality.

If this already exists, please point me in the right direction. 

Thanks!

**Comment by remonh87** [comment]
I studied: https://stripe.com/docs/connect/express-accounts and there is nothing needed from the Stripe sdk. All you need to do is do a couple of API call on the backend to Stripe and provide the account link. This accountlink can be opened using the `url_launcher` package or embedded in a webview.

Make sure you have specified a return link and that it is accepted by your app. https://docs.flutter.dev/development/ui/navigation/deep-linking. Hope that this helps.

**Comment by cedvdb** [comment]
I think what he meant was a native android view instead of having to open an external URL in the browser. This is not great UX, but might be required for security reasons ?

**Comment by remonh87** [comment]
@cedvdb  I think Stripe connect is not tailored for mobile native as far as I understood the docs.  Our library is mostly tailored for handling payments and we follow the feature set of https://github.com/stripe/stripe-react-native. You are right indeed that for native card payments we cannot build things ourselves easily since they need to be PCI compliant. That's why we use the native Stripe widgets.

**Comment by yassinsameh** [comment]
@remonh87 Does the package support embedings to create accounts? I couldn't find a resource.
My understanding Stripe now has 3 options to create Connect accounts, Via Url (Stripe handles everything),via Embeddings, via Custom API methods (Developer handles everything).
