### ISSUE TITLE
Web not working

### ISSUE THREAD

**Issue by eliudio** [flutter-stripe/flutter_stripe#847]
Doesn't work on web.

Reproduce: run the example with web, open the features that are supposed to work on web: you'll see it fails

**Comment by remonh87** [comment]
please can you follow the issue template so we can better address the issue? Which features do you mean? At the moment the web is very limited and we are working on a new version better maintainable version.

**Comment by Inovvia** [comment]
**Web not working**
Web hangs after submitting payment

**To Reproduce**
Steps to reproduce the behavior:
1. Follow steps in the read me
2. Run the web app
3. Choose either simple - using webhooks or without webhooks
4. [log] XMLHttpRequest error. after pressing pay now
![image](https://user-images.githubusercontent.com/70137651/183385671-58911337-34eb-4fa5-9d65-9653f6083189.png)
![image](https://user-images.githubusercontent.com/70137651/183385724-b532aeae-cd4f-4f3f-847f-f2a4bed8837a.png)
![image](https://user-images.githubusercontent.com/70137651/183386178-788da3bb-230d-4a35-aecd-4396088bf029.png)

**Expected behavior**
Payment works

**Smartphone / tablet**
 - OS: Windows 11
 - Package version: 4.0.0
 - Flutter version [e.g. 2.0.0.]

**Additional context**
Stripe CLI is running as well as the server

Chrome error:
:60628/#/:1 Access to XMLHttpRequest at 'http://localhost:4242/create-payment-intent' from origin 'http://localhost:60628' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Debug Error:
ChromeProxyService: Failed to evaluate expression '_xhrs.remove': InternalError: No frame with index 14.

**Comment by remonh87** [comment]
This has nothing to do with our library but has to do with the fact that Crhome doesn't allow http traffic. You need to configure CORS or you can use this https://pub.dev/packages/flutter_cors to test it out (not recommended for production)
