### ISSUE TITLE
Gpay button shows no processing while making payments.

### ISSUE THREAD

**Issue by Vikaskumar75** [flutter-stripe/flutter_stripe#882]
**Describe the bug**
Gpay button is blank while processing the payment. Even though the payment is successful.
**To Reproduce**
1. Using display payment sheet with Gpay enabled.
2. Try to make a payment.
3. Observe the time taken by Gpay button to show success.

**Expected behavior**
Must show an indicator that it is progress.
**Smartphone / tablet**
 - Samsung
 - Android 12
 - Package version: ^4.0.0
 - Flutter version : 3.0.5

**Additional context**
https://photos.google.com/share/AF1QipPkU22O_BmKqDI4u8T2JnD7X-WwsHaWt7bVp0qmWn_INyhOE-ZMahFyeRCO4l7ccw/photo/AF1QipO7uIhmP7Z4c7i5bVHUlfyBFlivPa9hTBMIbigx?key=MmJIUW1GMXNoS1pBMExyQ0Z4LUN0ckpNcjc2ZkdR

**Comment by jamesblasco** [comment]
I might afraid this issue comes from the GPay library itself when in dark mode. 

We are using the latest version of the plugin so I hope it is resolved in a future version.

| Light mode | Dark mode |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/19904063/185807112-6f32f438-424c-45e0-87b3-e326bb12c499.jpg" height="300" /> | <img src="https://user-images.githubusercontent.com/19904063/185807109-cc67bde7-e55b-447e-b1b5-3810d43f7bdf.jpg" height="300" /> |

**Comment by Vikaskumar75** [comment]
Thanks, a lot for the quick response.
Feels kind of relieved. Not sure why 😅

**Comment by jamesblasco** [comment]
I have checked with the latest version of the plugin 7.0.0 and there is a new design and the text is displayed correctly

 
![2022-12-10 16 19 35](https://user-images.githubusercontent.com/19904063/206862298-2555a4d2-fa88-43a2-aabc-5c8783f716cd.jpg)
