### ISSUE TITLE
Google Pay Button is not showing on presentPaymentSheet

### ISSUE THREAD

**Issue by YoucefSFPlus** [flutter-stripe/flutter_stripe#885]
**Describe the bug**
When I try to call presentPaymentSheet the carForm is showing good but I don't have the Google Pay button.
This is how I call it:

      var paymentIntent = await createPaymentIntent(amount, currency);
      await Stripe.instance.initPaymentSheet(
          paymentSheetParameters: SetupPaymentSheetParameters(
        applePay:  PaymentSheetApplePay(
                merchantCountryCode: 'FR',
              ),
        googlePay:  PaymentSheetGooglePay(
                merchantCountryCode: 'FR', currencyCode: 'EUR'),
        style: ThemeMode.system,
        merchantDisplayName: '128 Avenue',
        paymentIntentClientSecret: paymentIntent['client_secret'],
      ));
     await Stripe.instance.presentPaymentSheet();
Any error is displayed

package version : ^4.0.0

**Comment by jamesblasco** [comment]
Could you provide more information about:

  1. Are you using test or live environment? Same environment for both server and mobile
  2. Are you running a simulator or a real device? Does the simulator have google services?
  3. If in test mode, you should set: PaymentSheetGooglePay(merchantCountryCode: 'FR', currencyCode: 'EUR', **testEnv: true**),

I just tried last version on my device and works as expected: 

![IMAGE 2022-08-21 20:38:50](https://user-images.githubusercontent.com/19904063/185805920-7a2169d6-4a3b-4b26-9d03-cacac22d9357.jpg)

**Comment by ShwetaChauhan18** [comment]
@YoucefSFPlus : Make sure Google Pay is available in your device because if Gpay is not installed in your device it won't show.

**Comment by YoucefSFPlus** [comment]
@jamesblasco I tried in test and live mode in a real device, the environment is the same for server and mobile. When I used the test mode I correctly added **testEnv: true** but the Google Pay button still not showing up.
@ShwetaChauhan18 my Gpay is enabled on my device and I implemented exactly the same code in another app and every thing works good but this time it doesn't work.

**Comment by YoucefSFPlus** [comment]
Hi @jamesblasco @ShwetaChauhan18 ,
I forgot to add this line on my AndroidManifest 
`<meta-data android:name="com.google.android.gms.wallet.api.enabled" android:value="true" />`
that's why the Gpay button was not showing.

Now it worked perfectly, thank you for your help !

**Comment by nayanbabariya** [comment]
@ShwetaChauhan18 Not sure what you mean by `GPay not installed`. because GPay is the app for UPI payments and another app is `Google Wallet`.
I've configured the stripe sheet using this plugin, but the Stripe payment sheet cannot show the `GPay` button. however, using the pay plugin, I can show the PlatformPayButton and this button also opens the google pay native bottom sheet.
But I want to do this using the Stripe payment sheet. The `Apple Pay` button is showing on iOS.

I've gone through this doc => https://docs.page/flutter-stripe/flutter_stripe/sheet#7-optional---enable-google-pay-only-android
I've also installed the Google Wallet application.

but still no luck. could you help?
Thanks...
