### ISSUE TITLE
[stripe_checkout] Webview doesn't handle correctly intent:// when customer attempt to pay with iDeal

### ISSUE THREAD

**Issue by nerder** [flutter-stripe/flutter_stripe#949]
**Describe the bug**

When the customer chooses iDeal as the payment method they will be redirected to their bank app in order to confirm the payment, but when the webview receives a link with `intent://` as the protocol fails with `net:ERR_UNKNOWN_URL_SCHEME`

**To Reproduce**

Is not easy to reproduce with the entire iDeal flow because in test mode stripe doesn't actually redirect to the bank mobile app.

1. Inside `navigationDelegate` hardcode a URL that starts with "intent://"

**Expected behavior**

I expect to be able to open the customer's bank mobile app, and let them successfully pay

**Smartphone / tablet**
 - Device: Samsun s10+
 - OS: Android 12]
 - Package version: 5.0.0
 - Flutter version 3.3.2

cc @jamesblasco What's your take on this? I'm not sure what should be the correct way to handle this. Maybe simply replace every `intent://` with `https://`?

**Comment by jamesblasco** [comment]
Let me take a look into it tomorrow 👍🏻. Thanks for some much detailed info

**Comment by nerder** [comment]
No rush, thank you so much! 🙏🏼

**Comment by jamesblasco** [comment]
Hey! I have discussed also internally and think the best approach is to migrate `stripe_checkout`. Stripe has also deprecated the related apis in order to replace this feature with [Payment Links](https://stripe.com/es/payments/payment-links). I am working now in adding support for the [Payment Element](https://stripe.com/docs/payments/payment-element) for web, that would support similar features as PaymentSheet on native. After that we will probably will deprecate `stripe_checkout`.

Please reach me out if you have any trouble migrating to the `PaymentSheet`

**Comment by nerder** [comment]
That makes a lot of sense. I'll start the migration in a couple of weeks, and I'll let you know if I encounter any issues.

Thank you so much for this update!


_PS: I'll close my draft PR and also this issue since we have a clear path_
