### ISSUE TITLE
Add minimal example of taking a credit card payment payment.

### ISSUE THREAD

**Issue by bringbackthedog** [flutter-stripe/flutter_stripe#96]
I find it difficult to get started if you're not familiar with Stripe. How do you take a credit card payment? 
I'd like a minimum example of taking a credit card payment in Flutter. 

**Describe the solution you'd like**
Would be nice if there were a 1 file example of taking a payment in the docs or in the example on pub.dev. 

Thanks!

**Comment by remonh87** [comment]
I would recommend to go for the[ payment sheet:](https://github.com/flutter-stripe/flutter_stripe/blob/main/example/lib/screens/payment_sheet_screen.dart). Which is easier then the cardfield because it also handles 3d secure for you. We are working on improving the read me and docs atm and will keep your suggestion in mind.

**Comment by remonh87** [comment]
I think we catered enough for this now. Also checkout: https://flutterstripe.medium.com/announcing-the-flutter-sdk-for-stripe-1ba2b3ee667c
