### ISSUE TITLE
Keyboard loses focus on iOS

### ISSUE THREAD

**Issue by AndreHaueisen** [flutter-stripe/flutter_stripe#978]
**Describe the bug**
If the keyboard covers the `CardField` we lose focus making it impossible to type. It only happens on iOS

https://user-images.githubusercontent.com/13854934/196276449-277c7feb-83a5-4935-b5e6-9f2354c7bd66.mp4

![android_rec](https://user-images.githubusercontent.com/13854934/196276655-a02e2479-7c8b-4a96-825b-21c6ef966df8.gif)

**To Reproduce**
See the videos

**Expected behavior**
The keyboard should not be dismissed

**Smartphone / tablet**
 - Device: iPhone Se 2nd generation
 - OS: iOS 16
 - Package version: 5.1.0
 - Flutter version: 3.3.4

**Comment by jamesblasco** [comment]
Could you add a reproducible code example for the bug? I can't manage to reproduce it myself.

https://user-images.githubusercontent.com/19904063/206871914-7d4889ff-6966-40a6-88bc-de7443f6710f.MP4


One extra thing that I notice is that the CardField does not trigger the scrolling to keep himself visible when the keyboard appears. I will create a PR for that

**Comment by CripyIce** [comment]
Happens to me also when using the library `flutter_keyboard_visibility`.
I noticed that it happens because I wrap my entire `MaterialApp` with `KeyboardDismissOnTap` and set `dismissOnCapturedTaps: true`, like the following example:
```dart
KeyboardDismissOnTap(
      dismissOnCapturedTaps: true,
      child: MaterialApp(),
)
```

Once I set `dismissOnCapturedTaps` to `false` the `CardField` works as usual.

Any idea how to make it work without setting `dismissOnCapturedTaps` to `false`?
